#pragma once

#include "importer/MetaFile.hpp"
#include <filesystem>
#include <string>
#include <vector>

namespace StellarAlia::Import {

namespace fs = std::filesystem;

// One discovered primary asset (source file + its .sameta).
// .sanim and .saskel sidecar source files are NOT included here — they are
// generated by MeshImporter and cooked implicitly when the parent .glb is cooked.
struct AssetEntry {
    fs::path sourcePath;
    fs::path metaPath;
    MetaFile meta;
};

// Determines the asset type string from a file extension.
// Returns "" for unrecognised or sidecar-only extensions (.sanim, .saskel).
std::string AssetTypeFromExtension(const fs::path& ext);

// Recursively scans dir, generates a .sameta for every cookable primary asset
// that does not already have one, and returns all discovered entries.
// Existing .sameta files are never modified — UUIDs are stable.
std::vector<AssetEntry> ScanAndImport(const fs::path& dir);

} // namespace StellarAlia::Import
