#include "core/logs/Log.hpp"
#include "core/asset/AssetID.hpp"
#include "platform/window/GLFWWindow.hpp"
#include "platform/rhi/vulkan/VulkanDevice.hpp"
#include "platform/rhi/ShaderReflection.hpp"
#include "platform/rhi/ShaderReflectionIO.hpp"
#include "function/FrameUniforms.hpp"
#include "function/FrameUniformsBuffer.hpp"
#include "function/material/AttachmentKey.hpp"
#include "function/material/ShaderProgram.hpp"
#include "function/material/MaterialType.hpp"
#include "function/material/MaterialInstance.hpp"
#include "function/material/MaterialManager.hpp"
#include "function/render_graph/RenderGraph.hpp"
#include "resource/loaders/GltfLoader.hpp"
#include "resource/loaders/ImageLoader.hpp"
#include "resource/ResourceManager.hpp"
#include "GltfDemoPath.hpp"

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <stack>
#include <string>
#include <vector>

namespace fs = std::filesystem;
using namespace StellarAlia;
using namespace StellarAlia::RHI;
using namespace StellarAlia::Platform;
using namespace StellarAlia::Resource;

// ─── helpers ─────────────────────────────────────────────────────────────────

static std::vector<uint8_t> LoadSpv(const std::string& path) {
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f) { SA_LOG_ERROR("LoadSpv: cannot open '{}'", path); return {}; }
    const auto sz = static_cast<size_t>(f.tellg());
    f.seekg(0);
    std::vector<uint8_t> data(sz);
    f.read(reinterpret_cast<char*>(data.data()), static_cast<std::streamsize>(sz));
    return data;
}

// Read the uuid= line from a .sameta sidecar (auto-generated by ImportScanner).
static AssetID ReadMetaUUID(const fs::path& metaPath) {
    std::ifstream f(metaPath);
    if (!f) {
        SA_LOG_ERROR("ReadMetaUUID: cannot open '{}'", metaPath.string());
        return AssetID::Invalid();
    }
    std::string line;
    while (std::getline(f, line)) {
        if (line.rfind("uuid=", 0) == 0)
            return AssetID::FromString(std::string_view(line).substr(5));
    }
    SA_LOG_ERROR("ReadMetaUUID: no 'uuid=' line found in '{}'", metaPath.string());
    return AssetID::Invalid();
}

// ─── PBR MaterialType builder ─────────────────────────────────────────────────
// MaterialParams layout (48 bytes, matches pbr.frag set=1 binding=0):
//   vec4  baseColorFactor    offset= 0, size=16
//   float roughnessFactor    offset=16, size= 4
//   float metallicFactor     offset=20, size= 4
//   float normalScale        offset=24, size= 4
//   float occlusionStrength  offset=28, size= 4
//   vec3  emissiveFactor     offset=32, size=12
//   float _pad               offset=44, size= 4

static std::unique_ptr<MaterialType> BuildPbrType(IRHIDevice*                 device,
                                                   RHIDescLayoutHandle         frameLayout,
                                                   const std::vector<uint8_t>& vertSpv,
                                                   const ShaderReflection&     vertRefl,
                                                   const std::vector<uint8_t>& fragSpv,
                                                   const ShaderReflection&     fragRefl) {
    auto type  = std::make_unique<MaterialType>();
    type->name = "PBR";

    // ── Derive uboSize from set=1 binding=0 UBO block size in merged reflection.
    // ── Derive texture slots from all set=1 Texture2D/TextureCube bindings.
    // (We merge now to inspect, then the ShaderProgram will merge again internally.)
    const ShaderReflection merged = MergeReflections(vertRefl, fragRefl);

    if (auto ubo = merged.FindBinding(1, 0)) {
        type->uboSize = ubo->blockSize;
    } else {
        SA_LOG_WARN("BuildPbrType: no set=1 binding=0 UBO found; uboSize=0");
    }

    // Auto-derive params from UBO member reflection.
    if (auto ubo = merged.FindBinding(1, 0)) {
        for (const auto& m : ubo->members)
            type->params.push_back({m.name, m.offset, m.size});
    } else {
        SA_LOG_WARN("BuildPbrType: no set=1 binding=0 UBO — params table is empty");
    }

    // Collect all set=1 texture/sampler bindings sorted by binding index.
    {
        std::vector<const ShaderBindingDesc*> texBindings;
        for (const auto& b : merged.bindings) {
            if (b.set != 1) continue;
            if (b.type == RHIDescriptorType::Texture2D  ||
                b.type == RHIDescriptorType::TextureCube ||
                b.type == RHIDescriptorType::Sampler)
                texBindings.push_back(&b);
        }
        std::sort(texBindings.begin(), texBindings.end(),
                  [](const ShaderBindingDesc* a, const ShaderBindingDesc* b){
                      return a->binding < b->binding; });
        uint32_t slotIdx = 0;
        for (const auto* b : texBindings)
            type->textures.push_back({b->name, b->binding, slotIdx++});
    }

    type->defaultCullMode   = RHICullMode::Back;
    type->defaultDepthTest  = true;
    type->defaultDepthWrite = true;

    ShaderProgram::Desc pd;
    pd.vertSpv     = vertSpv;
    pd.vertRefl    = vertRefl;
    pd.fragSpv     = fragSpv;
    pd.fragRefl    = fragRefl;
    pd.frameLayout = frameLayout;

    if (!type->shader.Load(device, pd)) return nullptr;
    return type;
}

// ─── Draw command ─────────────────────────────────────────────────────────────

struct DrawCmd {
    uint32_t  submeshIndex;
    glm::mat4 worldTransform;
};

// ─── main ─────────────────────────────────────────────────────────────────────

int main() {
    Core::Log::Initialize();
    SA_LOG_INFO("=== glTF Material Demo (MetalRoughSpheres) ===");

    // ── Resolve asset paths ───────────────────────────────────────────────────
    const fs::path assetsDir   = GltfDemo::SA_ASSETS_DIR;
    const fs::path cookCacheDir = GltfDemo::COOK_CACHE_DIR;
    const std::string shaderDir = GltfDemo::BUILTIN_SHADER_DIR;

    const fs::path glbPath  = assetsDir / "models/builtin/MetalRoughSpheres.glb";
    const fs::path metaPath = fs::path(glbPath.string() + ".sameta");

    if (!fs::exists(glbPath)) {
        SA_LOG_CRITICAL("GLB not found: {}", glbPath.string());
        return 1;
    }
    if (!fs::exists(metaPath)) {
        SA_LOG_CRITICAL(".sameta not found: {} — run the cook tool first", metaPath.string());
        return 1;
    }

    // ── Read UUID from auto-generated .sameta ─────────────────────────────────
    AssetID meshId = ReadMetaUUID(metaPath);
    if (!meshId.IsValid()) {
        SA_LOG_CRITICAL("Failed to read AssetID from .sameta");
        return 1;
    }
    SA_LOG_INFO("Mesh AssetID: {}", meshId.ToString());

    // ── Load SceneData via GltfLoader (hierarchy + materials) ────────────────
    auto sceneOpt = GltfLoader::Load(glbPath.string());
    if (!sceneOpt) {
        SA_LOG_CRITICAL("GltfLoader failed for '{}'", glbPath.string());
        return 1;
    }
    const SceneData& scene = *sceneOpt;
    SA_LOG_INFO("Scene loaded: {} meshes, {} materials, {} nodes",
                scene.meshes.size(), scene.materials.size(), scene.nodes.size());

    // ── Build mesh-to-submesh-start lookup ────────────────────────────────────
    // CookedMesh flattens all primitives across all meshes in source order.
    std::vector<uint32_t> meshSubmeshStart(scene.meshes.size());
    {
        uint32_t running = 0;
        for (size_t i = 0; i < scene.meshes.size(); ++i) {
            meshSubmeshStart[i] = running;
            running += static_cast<uint32_t>(scene.meshes[i].primitives.size());
        }
    }

    // ── Window ────────────────────────────────────────────────────────────────
    auto window = GLFWWindow::Create({
        .width=1280, .height=720,
        .title="StellarAlia - glTF Material Demo",
        .resizable=true,
    });
    if (!window) { SA_LOG_CRITICAL("Window creation failed"); return 1; }

    // ── Device ────────────────────────────────────────────────────────────────
    auto device = VulkanDevice::Create({
        .windowHandle        = {window->GetNativeHandle()},
        .swapchainWidth      = window->GetWidth(),
        .swapchainHeight     = window->GetHeight(),
        .swapchainImageCount = 2,
        .vsync               = true,
        .enableValidation    = true,
    });
    if (!device) { SA_LOG_CRITICAL("Device creation failed"); return 1; }

    // ── Resource manager — loads cooked mesh onto GPU ─────────────────────────
    ResourceManager resMgr;
    resMgr.Init(cookCacheDir, device.get());

    const GPUMesh* gpuMesh = resMgr.LoadMesh(meshId);
    if (!gpuMesh || !gpuMesh->IsValid()) {
        SA_LOG_CRITICAL("Failed to load cooked mesh from cook cache");
        resMgr.Shutdown();
        device->WaitIdle();
        return 1;
    }
    SA_LOG_INFO("GPU mesh loaded: {} vertices, {} indices, {} submeshes",
                gpuMesh->vertexCount, gpuMesh->indexCount, gpuMesh->subMeshes.size());

    // ── DFS scene graph → draw command list ───────────────────────────────────
    std::vector<DrawCmd> drawCmds;
    {
        struct Frame { uint32_t nodeIdx; glm::mat4 parentXform; };
        std::stack<Frame> stack;
        for (uint32_t root : scene.rootNodes)
            stack.push({root, glm::mat4(1.f)});

        while (!stack.empty()) {
            auto [nodeIdx, parentXform] = stack.top();
            stack.pop();
            const SceneNode& node = scene.nodes[nodeIdx];
            glm::mat4 worldXform = parentXform * node.localTransform;

            if (node.meshIndex >= 0) {
                const uint32_t mIdx    = static_cast<uint32_t>(node.meshIndex);
                const uint32_t firstSub = meshSubmeshStart[mIdx];
                const uint32_t numSub  = static_cast<uint32_t>(scene.meshes[mIdx].primitives.size());
                for (uint32_t s = 0; s < numSub; ++s)
                    drawCmds.push_back({firstSub + s, worldXform});
            }
            for (uint32_t child : node.children)
                stack.push({child, worldXform});
        }
    }
    SA_LOG_INFO("Draw commands: {}", drawCmds.size());

    // ── Frame uniforms (set=0) ────────────────────────────────────────────────
    FrameUniformsBuffer frameUniforms;
    frameUniforms.Init(device.get());

    // ── Depth texture ─────────────────────────────────────────────────────────
    auto createDepthTex = [&](uint32_t w, uint32_t h) {
        RHITextureDesc dd{};
        dd.width    = w;  dd.height = h;
        dd.format   = RHIFormat::D32F;
        dd.usage    = RHITextureUsage::DepthStencil;
        dd.debugName = "SceneDepth";
        return device->CreateTexture(dd);
    };
    RHITextureHandle depthTex = createDepthTex(window->GetWidth(), window->GetHeight());

    // ── Shaders ───────────────────────────────────────────────────────────────
    auto vertSpv = LoadSpv(shaderDir + "/pbr.vert.spv");
    auto fragSpv = LoadSpv(shaderDir + "/pbr.frag.spv");
    if (vertSpv.empty() || fragSpv.empty()) {
        SA_LOG_CRITICAL("Failed to load pbr shader .spv — rebuild the project first");
        device->DestroyTexture(depthTex);
        frameUniforms.Shutdown();
        resMgr.Shutdown();
        device->WaitIdle();
        return 1;
    }

    ShaderReflection vertRefl, fragRefl;
    if (!ShaderReflectionIO::LoadFromFile(fs::path(shaderDir) / "pbr.vert.refl", vertRefl) ||
        !ShaderReflectionIO::LoadFromFile(fs::path(shaderDir) / "pbr.frag.refl", fragRefl)) {
        SA_LOG_CRITICAL("Failed to load pbr shader .refl — rebuild the project first");
        device->DestroyTexture(depthTex);
        frameUniforms.Shutdown();
        resMgr.Shutdown();
        device->WaitIdle();
        return 1;
    }
    SA_LOG_INFO("PBR reflection loaded: vert={} bindings, frag={} bindings",
                vertRefl.bindings.size(), fragRefl.bindings.size());

    // ── Default 1×1 white texture (for unset sampler slots) ──────────────────
    RHITextureHandle whiteTex;
    {
        RHITextureDesc td{};
        td.width = 1; td.height = 1;
        td.format = RHIFormat::RGBA8_UNORM;
        td.usage  = RHITextureUsage::Sampled;
        td.debugName = "White1x1";
        whiteTex = device->CreateTexture(td);
        const uint32_t white = 0xFFFFFFFFu;
        device->UploadTextureData(whiteTex, &white, 4);
    }

    // ── Upload scene images from GLB to GPU textures ──────────────────────────
    // GltfLoader already decoded embedded images into scene.images[i].pixels (RGBA8).
    // We upload each one now so material instances can bind them as samplers.
    std::vector<RHITextureHandle> gpuImages;
    gpuImages.reserve(scene.images.size());
    for (size_t i = 0; i < scene.images.size(); ++i) {
        const ImageData& img = scene.images[i];
        if (!img.IsValid() || img.pixels.empty()) {
            SA_LOG_WARN("Scene image {}: invalid or empty — using white fallback", i);
            gpuImages.push_back(whiteTex);
            continue;
        }
        RHITextureDesc td{};
        td.width     = img.width;
        td.height    = img.height;
        td.format    = RHIFormat::RGBA8_UNORM;
        td.usage     = RHITextureUsage::Sampled;
        const std::string dbgName = img.path.empty() ? ("SceneImage_" + std::to_string(i)) : img.path;
        td.debugName = dbgName.c_str();
        RHITextureHandle tex = device->CreateTexture(td);
        device->UploadTextureData(tex, img.pixels.data(), img.pixels.size());
        gpuImages.push_back(tex);
        SA_LOG_DEBUG("Uploaded scene image {}: {}×{}", i, img.width, img.height);
    }

    // Helper: resolve a TextureRef to a GPU handle (whiteTex if no image)
    auto resolveTexture = [&](const TextureRef& ref) -> RHITextureHandle {
        if (ref.imageIndex >= 0 && static_cast<size_t>(ref.imageIndex) < gpuImages.size())
            return gpuImages[ref.imageIndex];
        return whiteTex;
    };

    // ── MaterialManager + PBR type ────────────────────────────────────────────
    MaterialManager matMgr;
    matMgr.Init(device.get(), whiteTex);

    auto pbrType = BuildPbrType(device.get(), frameUniforms.GetLayout(),
                                vertSpv, vertRefl, fragSpv, fragRefl);
    if (!pbrType) {
        SA_LOG_CRITICAL("Failed to build PBR material type");
        device->DestroyTexture(whiteTex);
        device->DestroyTexture(depthTex);
        frameUniforms.Shutdown();
        resMgr.Shutdown();
        device->WaitIdle();
        return 1;
    }
    matMgr.RegisterType(std::move(pbrType));

    // ── Create one MaterialInstance per glTF material ─────────────────────────
    std::vector<std::unique_ptr<MaterialInstance>> matInstances;
    matInstances.reserve(scene.materials.size());
    for (const MaterialData& md : scene.materials) {
        auto inst = matMgr.CreateInstance("PBR");
        if (!inst) { SA_LOG_ERROR("Failed to create material instance for '{}'", md.name); continue; }

        // UBO params — SetParam<T> deduces size from T, writes to reflection-derived offset
        inst->SetParam("baseColorFactor",   md.baseColorFactor);
        inst->SetParam("roughnessFactor",   md.roughnessFactor);
        inst->SetParam("metallicFactor",    md.metallicFactor);
        inst->SetParam("normalScale",       md.normalScale);
        inst->SetParam("occlusionStrength", md.occlusionStrength);
        inst->SetParam("emissiveFactor",    md.emissiveFactor);

        // Texture bindings — resolved from scene.images via imageIndex
        inst->SetTexture("t_BaseColor",         resolveTexture(md.baseColorTexture));
        inst->SetTexture("t_Normal",            resolveTexture(md.normalTexture));
        inst->SetTexture("t_MetallicRoughness", resolveTexture(md.metallicRoughnessTexture));
        inst->SetTexture("t_Occlusion",         resolveTexture(md.occlusionTexture));
        inst->SetTexture("t_Emissive",          resolveTexture(md.emissiveTexture));

        SA_LOG_DEBUG("Material '{}': baseColor=[{:.2f},{:.2f},{:.2f},{:.2f}] "
                     "metallic={:.2f} rough={:.2f}",
                     md.name,
                     md.baseColorFactor.r, md.baseColorFactor.g,
                     md.baseColorFactor.b, md.baseColorFactor.a,
                     md.metallicFactor, md.roughnessFactor);

        matInstances.push_back(std::move(inst));
    }

    // Fallback instance used when materialIndex == -1 or out of range
    auto fallbackMat = matMgr.CreateInstance("PBR");
    fallbackMat->SetVec4("baseColorFactor", {0.8f, 0.8f, 0.8f, 1.f});
    fallbackMat->SetFloat("roughnessFactor", 0.5f);
    fallbackMat->SetFloat("metallicFactor",  0.f);
    fallbackMat->SetFloat("normalScale",     1.f);
    fallbackMat->SetFloat("occlusionStrength", 1.f);

    SA_LOG_INFO("Loaded {} material instances", matInstances.size());

    // ── Load HDR environment map + BRDF LUT ───────────────────────────────────
    // Helper: load a .hdr file and upload as RGBA32F texture (converting from RGB).
    auto loadHDR = [&](const fs::path& hdrPath, const char* dbgName) -> RHITextureHandle {
        auto imgOpt = ImageLoader::LoadHDR(hdrPath.string());
        if (!imgOpt || !imgOpt->IsValid() || imgOpt->pixelsHDR.empty()) {
            SA_LOG_ERROR("loadHDR: failed to load '{}'", hdrPath.string());
            return whiteTex;
        }
        const ImageData& img = *imgOpt;
        const uint32_t ch = img.channels;
        const uint32_t npx = img.width * img.height;

        // Convert to RGBA32F (pad alpha = 1.0 if only 3 channels)
        std::vector<float> rgba(npx * 4);
        for (uint32_t p = 0; p < npx; ++p) {
            rgba[p*4+0] = (ch > 0) ? img.pixelsHDR[p*ch+0] : 0.f;
            rgba[p*4+1] = (ch > 1) ? img.pixelsHDR[p*ch+1] : 0.f;
            rgba[p*4+2] = (ch > 2) ? img.pixelsHDR[p*ch+2] : 0.f;
            rgba[p*4+3] = (ch > 3) ? img.pixelsHDR[p*ch+3] : 1.f;
        }

        RHITextureDesc td{};
        td.width = img.width; td.height = img.height;
        td.format    = RHIFormat::RGBA32F;
        td.usage     = RHITextureUsage::Sampled;
        td.debugName = dbgName;
        RHITextureHandle tex = device->CreateTexture(td);
        device->UploadTextureData(tex, rgba.data(), rgba.size() * sizeof(float));
        SA_LOG_INFO("HDR loaded: {} ({}x{})", hdrPath.filename().string(), img.width, img.height);
        return tex;
    };

    const fs::path hdriDir = assetsDir / "hdri";
    RHITextureHandle envMapTex = loadHDR(hdriDir / "grasslands_sunset_4k.hdr", "EnvMap");
    RHITextureHandle brdfLutTex = loadHDR(hdriDir / "brdf_schilk.hdr",          "BrdfLut");

    frameUniforms.SetIBLTextures(brdfLutTex, whiteTex, envMapTex);

    // ── Skybox ShaderProgram ──────────────────────────────────────────────────
    ShaderProgram skyboxProgram;
    {
        auto skyboxVertSpv = LoadSpv(shaderDir + "/skybox.vert.spv");
        auto skyboxFragSpv = LoadSpv(shaderDir + "/skybox.frag.spv");
        ShaderReflection skyboxVertRefl, skyboxFragRefl;

        const bool skyboxOk =
            !skyboxVertSpv.empty() && !skyboxFragSpv.empty() &&
            ShaderReflectionIO::LoadFromFile(
                fs::path(shaderDir) / "skybox.vert.refl", skyboxVertRefl) &&
            ShaderReflectionIO::LoadFromFile(
                fs::path(shaderDir) / "skybox.frag.refl", skyboxFragRefl);

        if (skyboxOk) {
            ShaderProgram::Desc pd;
            pd.vertSpv     = skyboxVertSpv;
            pd.vertRefl    = skyboxVertRefl;
            pd.fragSpv     = skyboxFragSpv;
            pd.fragRefl    = skyboxFragRefl;
            pd.frameLayout = frameUniforms.GetLayout();
            if (skyboxProgram.Load(device.get(), pd))
                SA_LOG_INFO("Skybox ShaderProgram loaded");
            else
                SA_LOG_ERROR("Skybox ShaderProgram load FAILED");
        } else {
            SA_LOG_WARN("Skybox shaders/.refl not found — skybox disabled (rebuild needed)");
        }
    }

    // AttachmentKey for each pipeline variant (built once, reused every frame).
    AttachmentKey skyboxKey;
    skyboxKey.colorFormats[0] = device->GetSwapchainFormat();
    skyboxKey.colorCount      = 1;
    skyboxKey.depthFormat     = RHIFormat::Undefined;  // no depth attachment

    AttachmentKey geoKey;
    geoKey.colorFormats[0] = device->GetSwapchainFormat();
    geoKey.colorCount      = 1;
    geoKey.depthFormat     = RHIFormat::D32F;

    // ── Render loop ───────────────────────────────────────────────────────────
    SA_LOG_INFO("GltfMaterialDemo: entering render loop ({} draw calls per frame)", drawCmds.size());

    float    time  = 0.f;
    uint32_t lastW = window->GetWidth(), lastH = window->GetHeight();

    while (!window->ShouldClose()) {
        window->PollEvents();

        const uint32_t W = window->GetWidth(), H = window->GetHeight();
        if (W != lastW || H != lastH) {
            lastW = W; lastH = H;
            device->WaitIdle();
            device->DestroyTexture(depthTex);
            device->ResizeSwapchain(lastW, lastH);
            depthTex = createDepthTex(lastW, lastH);
        }

        IRHICommandList* cmd = device->BeginFrame();
        if (!cmd) continue;

        const uint32_t w  = device->GetSwapchainWidth();
        const uint32_t h  = device->GetSwapchainHeight();
        const uint32_t fi = device->GetCurrentFrameIndex();

        // ── Upload frame uniforms ─────────────────────────────────────────────
        time += 0.016f;

        FrameUniforms fu{};
        // Wide view: MetalRoughSpheres is roughly 10 units wide
        fu.view      = glm::lookAt(glm::vec3(0.f, 2.f, 15.f),
                                    glm::vec3(0.f, 2.f,  0.f),
                                    glm::vec3(0.f, 1.f,  0.f));
        fu.proj      = glm::perspective(glm::radians(50.f),
                                         static_cast<float>(w) / static_cast<float>(h),
                                         0.01f, 200.f);
        fu.proj[1][1] *= -1.f;   // flip Y for Vulkan NDC
        fu.viewProj    = fu.proj * fu.view;
        fu.invViewProj = glm::inverse(fu.viewProj);
        fu.cameraPos   = glm::vec3(0.f, 2.f, 15.f);
        fu.time        = time;
        fu.resolution  = glm::vec2(static_cast<float>(w), static_cast<float>(h));
        fu.deltaTime   = 0.016f;

        LightUniforms lu{};
        lu.direction        = glm::normalize(glm::vec3(1.f, -1.f, 0.5f));
        lu.intensity        = 3.f;
        lu.color            = glm::vec3(1.f, 0.98f, 0.95f);
        lu.ambientColor     = glm::vec3(0.05f, 0.05f, 0.08f);
        lu.ambientIntensity = 1.f;

        frameUniforms.Upload(fi, fu, lu);

        // ── Build RenderGraph for this frame ─────────────────────────────────
        RenderGraph rg;
        rg.Reset();

        // Import external resources.
        // Swapchain: already in RenderTarget state after BeginFrame's clear.
        // Depth: starts Undefined each frame — the geometry pass clears it.
        const auto rgSwapchain = rg.ImportTexture("Swapchain",
            device->GetSwapchainTexture(),
            RHIResourceState::RenderTarget,
            RHIResourceState::RenderTarget);
        const auto rgDepth = rg.ImportTexture("Depth",
            depthTex,
            RHIResourceState::Undefined,
            RHIResourceState::Undefined);

        const RHIDescSetHandle frameDescSet =
            frameUniforms.GetDescriptorSet(fi % FrameUniformsBuffer::MAX_FRAMES);

        // ── Pass 1: Skybox ────────────────────────────────────────────────────
        // Fullscreen triangle, no depth attachment (avoids Intel iGPU issues).
        // RG emits the RenderTarget→RenderTarget memory barrier before Pass 2.
        if (skyboxProgram.IsLoaded()) {
            RHIPipelineHandle skyboxPipeline = skyboxProgram.GetOrCreatePipeline(
                device.get(), skyboxKey,
                RHICullMode::None, RHIBlendMode::Opaque,
                /*depthTest*/false, /*depthWrite*/false, /*noVertexInput*/true);

            rg.AddPass("Skybox",
                [rgSwapchain](RGPassBuilder& b) { b.Write(rgSwapchain); },
                [rgSwapchain, skyboxPipeline, frameDescSet, w, h]
                (IRHICommandList& cmd, const RGResources& res) {
                    RHIRenderPassDesc pd{};
                    pd.colorAttachments[0].texture     = res.Get(rgSwapchain);
                    pd.colorAttachments[0].clearOnLoad = false;
                    pd.colorAttachmentCount = 1;
                    pd.hasDepth = false;
                    pd.width = w;  pd.height = h;
                    cmd.BeginRenderPass(pd);
                    cmd.SetViewport({0.f, 0.f, float(w), float(h)});
                    cmd.SetScissor({0, 0, w, h});
                    cmd.SetPipeline(skyboxPipeline);
                    cmd.SetDescriptorSet(0, frameDescSet);
                    cmd.Draw(3, 1, 0, 0);
                    cmd.EndRenderPass();
                });
        }

        // ── Pass 2: Geometry ──────────────────────────────────────────────────
        // LOADs skybox color (clearOnLoad=false), clears depth.
        // Push constant size is read from the merged shader reflection so the
        // demo doesn't hard-code the 64-byte mat4 size.
        rg.AddPass("Geometry",
            [rgSwapchain, rgDepth](RGPassBuilder& b) {
                b.Write(rgSwapchain);
                b.WriteDepth(rgDepth);
            },
            [&, rgSwapchain, rgDepth, frameDescSet, w, h]
            (IRHICommandList& cmd, const RGResources& res) {
                RHIRenderPassDesc pd{};
                pd.colorAttachments[0].texture     = res.Get(rgSwapchain);
                pd.colorAttachments[0].clearOnLoad = false;  // LOAD skybox pixels
                pd.colorAttachmentCount            = 1;
                pd.hasDepth                        = true;
                pd.depthAttachment.texture         = res.Get(rgDepth);
                pd.depthAttachment.clearOnLoad     = true;
                pd.depthAttachment.clearDepth      = 1.f;
                pd.width = w;  pd.height = h;

                cmd.BeginRenderPass(pd);
                cmd.SetViewport({0.f, 0.f, float(w), float(h)});
                cmd.SetScissor({0, 0, w, h});
                cmd.SetVertexBuffer(0, gpuMesh->vertexBuffer, 0);
                cmd.SetIndexBuffer(gpuMesh->indexBuffer, 0, false);

                RHIPipelineHandle lastPipeline{};
                for (const DrawCmd& dc : drawCmds) {
                    if (dc.submeshIndex >= gpuMesh->subMeshes.size()) continue;
                    const GPUSubMesh& sub = gpuMesh->subMeshes[dc.submeshIndex];

                    MaterialInstance* mat = fallbackMat.get();
                    if (sub.materialIndex >= 0 &&
                        static_cast<size_t>(sub.materialIndex) < matInstances.size() &&
                        matInstances[sub.materialIndex])
                    {
                        mat = matInstances[sub.materialIndex].get();
                    }

                    RHIPipelineHandle pipeline = mat->GetPipeline(device.get(), geoKey);
                    if (!pipeline.IsValid()) continue;

                    if (!(pipeline == lastPipeline)) {
                        cmd.SetPipeline(pipeline);
                        cmd.SetDescriptorSet(0, frameDescSet);
                        lastPipeline = pipeline;
                    }
                    mat->Bind(&cmd);

                    // Push constant size from reflection — no magic numbers.
                    const uint32_t pcSize =
                        mat->GetType()->shader.GetMergedReflection().pushConstantSize;
                    if (pcSize > 0)
                        cmd.SetPushConstants(&dc.worldTransform, pcSize,
                                             RHIShaderStage::Vertex);

                    cmd.DrawIndexed(sub.indexCount, 1,
                                    sub.firstIndex, sub.vertexOffset, 0);
                }
                cmd.EndRenderPass();
            });

        rg.Compile();
        rg.Execute(*device, *cmd);

        device->EndFrame();
        device->Present();
    }

    // ── Shutdown ──────────────────────────────────────────────────────────────
    device->WaitIdle();

    skyboxProgram.Unload(device.get());
    fallbackMat.reset();
    matInstances.clear();
    matMgr.Shutdown();
    for (RHITextureHandle tex : gpuImages)
        if (tex != whiteTex) device->DestroyTexture(tex);
    if (envMapTex  != whiteTex) device->DestroyTexture(envMapTex);
    if (brdfLutTex != whiteTex) device->DestroyTexture(brdfLutTex);
    device->DestroyTexture(whiteTex);
    device->DestroyTexture(depthTex);
    frameUniforms.Shutdown();
    resMgr.Shutdown();

    device.reset();
    window.reset();

    SA_LOG_INFO("GltfMaterialDemo: clean shutdown");
    Core::Log::Shutdown();
    return 0;
}
