<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="StellarAlia.Runtime">
      <HintPath>$(StellarAliaManaged)\StellarAlia.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <!-- Scripts auto-discovered by MSBuild **/*.cs glob -->
  </ItemGroup>

</Project>
