#pragma once

#include <filesystem>
#include <string>
#include <vector>

namespace StellarAlia::ShaderCook {

// ─────────────────────────────────────────────────────────────────────────────
// Configuration for cooking .saglsl custom shading model files.
// ─────────────────────────────────────────────────────────────────────────────
struct CookConfig {
    std::string              glslcPath;     // path to glslc executable
    std::string              reflToolPath;  // path to ShaderReflectTool executable
    std::vector<std::string> includePaths;  // extra -I paths for glslc
    bool                     force = false; // recompile even when outputs are newer
};

struct CookResult {
    bool                     success     = true;
    int                      modelCount  = 0;    // number of custom shading models found
    std::vector<std::string> failedModels;        // model names that failed compilation
};

// ─────────────────────────────────────────────────────────────────────────────
// API
// ─────────────────────────────────────────────────────────────────────────────

// Returns true when scanDir contains at least one .saglsl file.
bool HasSaglslFiles(const std::filesystem::path& scanDir);

// Parse, generate dispatch GLSL, and compile all .saglsl files in scanDir.
// modelCount=0 when no .saglsl files are present (success=true in that case too).
// Generates shading_model_ids.glsl + shading_dispatch.glsl in dispatchOutDir.
// Per-entry SPV + .refl outputs land in spvOutDir.
CookResult CookDirectory(const std::filesystem::path& scanDir,
                          const std::filesystem::path& spvOutDir,
                          const std::filesystem::path& dispatchOutDir,
                          const CookConfig&             cfg);

// Recompile deferred_lighting.frag with the project dispatch generated by CookDirectory.
// fragSrcPath   — engine source file, e.g. ENGINE_SHADER_SRC_DIR/deferred_lighting.frag
// dispatchDir   — directory with generated shading_dispatch.glsl (= dispatchOutDir above)
// outSpvPath    — output path for the recompiled .spv
// includePaths  — extra -I paths forwarded to glslc
bool RecompileDeferredLighting(const std::filesystem::path&  fragSrcPath,
                                const std::filesystem::path&  dispatchDir,
                                const std::filesystem::path&  outSpvPath,
                                const std::string&             glslcPath,
                                const std::vector<std::string>& includePaths = {});

} // namespace StellarAlia::ShaderCook
